project_prefix  = "boot4"
region          = "us-east-1"
vpc_cidr_block  = "10.0.32.0/20"
environment     = "prod"
ami             = "ami-0afc8198d221d15ea"
instance_type   = "t2.medium"
aws_iam_instance_profile = "boot4-EC2AdminAccessProfile"