project_prefix  = "boot4"
region          = "us-east-1"
vpc_cidr_block  = "10.0.0.0/20"
environment     = "dev"
ami             = "ami-0231dec57f47ccaa8"
instance_type   = "t2.medium"
aws_iam_instance_profile = "boot4-EC2AdminAccessProfile"